# This github workflow will automatically update docker image tags of lip-depl in the datakaveri/iudx-deployment repository files,
# whenever a docker image is pushed to ghcr.io/datakaveri/lip-depl with the tag 5.6.0-alpha. This will update the master/main branch.

name: Update LIP docker image tags (master)

# Trigger on new package published to registry
on:
  registry_package:
    types: [published]

permissions:
  packages: read

jobs:
  update-main:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: datakaveri/iudx-deployment
        token: "${{ secrets.JENKINS_UPDATE }}"
        fetch-depth: 0

    - name: Update LIP docker image tags for master
      env: 
        GH_TOKEN: ${{ secrets.JENKINS_UPDATE }}
      run: | 
        export newtag5_6_0_alpha=`(head -n1 <(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/datakaveri/packages/container/lip-depl/versions | jq ' .[].metadata.container.tags[0]' | grep 5.6.0-alpha | sed -e 's/^"//' -e 's/"$//'))`
        export oldtag5_6_0_alpha=`yq -r .services.lip.image Docker-Swarm-deployment/single-node/lip/lip-stack.yaml | cut -d : -f 2`

        if [ "$newtag5_6_0_alpha" != "$oldtag5_6_0_alpha" ]
        then
          git checkout master
          git checkout -b lip-automatic-updates/$newtag5_6_0_alpha
          
          sed -i s/$oldtag5_6_0_alpha/$newtag5_6_0_alpha/g Docker-Swarm-deployment/single-node/lip/lip-stack.yaml
          
          export oldappversion=`yq -r .version K8s-deployment/Charts/latest-ingestion-pipeline/Chart.yaml`
          export newappversion=`yq -r .version K8s-deployment/Charts/latest-ingestion-pipeline/Chart.yaml | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'`
          
          sed -i s/$oldappversion/$newappversion/g K8s-deployment/Charts/latest-ingestion-pipeline/Chart.yaml
          sed -i s/$oldtag5_6_0_alpha/$newtag5_6_0_alpha/g K8s-deployment/Charts/latest-ingestion-pipeline/values.yaml
          
          git add Docker-Swarm-deployment/single-node/lip/lip-stack.yaml K8s-deployment/Charts/latest-ingestion-pipeline/values.yaml K8s-deployment/Charts/latest-ingestion-pipeline/Chart.yaml
          git commit --allow-empty -m "updated LIP docker image tag to $newtag5_6_0_alpha"
          git push --set-upstream origin lip-automatic-updates/$newtag5_6_0_alpha
          
          gh pr create -R datakaveri/iudx-deployment --base master --fill 
        fi
